### PR TITLE
Changes for ST3

### PR DESCRIPTION
**Pull request by pahlers**
Here are changes for ST3. First draft. It kills the version for ST2, so please don't merge.

I didn't test it really well. It would be nice if you included a unit test ;-). 'jQuery' and 'ace' downloaded very well. '666' went wrong. I didn't figure out why. Maybe you can.
- Changed for python3 packages
- Added file decode
- Added specific urllib exception

### CODE REVIEW

**Comment by benschwarz** [comment]
Thanks Peter, I'll check the changes against st2. I don't have a license for 3 yet, I'd never bothered to upgrade.
—

**Comment by benschwarz** [comment]
As you'll note, I totally restructured the codebase — hopefully its a step to making it more maintainable now that I've hacked out that all important first working version. 

I'll come back around to trying to implement your changes, or seeing what we can do to make it work in both ST2 & 3 at once.

… at a high level, can you explain why its not working in ST3?

**Comment by pahlers** [comment]
Some packages renamed and/or have other structures:
- package urllib2 become urllib
- package StringIO become io

urllib got another structure:
First:

``` python
urllib2.urlopen()
urllib2.Request()
```

Now:

``` python
urllib.request.urlopen()
urllib.request.Request()
```

You can solve these with the next pattern:

``` python
try:
    # Python 3
    from io import StringIO 
except ImportError:
    # Python 2
    from StringIO import StringIO
```

Example:

``` python
try:
    # Python 3
    import urllib.request as req
except ImportError:
    # Python 2
    import urllib2 as req

try:
    # Python 3
    from io import StringIO 
except ImportError:
    # Python 2
    from StringIO import StringIO

request = req.Request(uri)
respons = req.urlopen(request)
```

**Comment by benschwarz** [comment]
Great. I'll consider all of that and have a go at working on ST3.
I downloaded a copy and got started, but right now I'm getting

```
reloading plugin Bower.Bower
Traceback (most recent call last):
  File "/Volumes/Sublime Text/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 72, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Users/benschwarz/Library/Application Support/Sublime Text 3/Installed Packages/Bower.sublime-package/Bower.py", line 5, in <module>
ImportError: No module named 'bower'

```

So I'll have to start from there and figure it out.  

Thanks so much for your assistance so far!

**Comment by pahlers** [comment]
I added a st2/3 example.

**Comment by benschwarz** [comment]
Legendary!
That'll really help a lot - hopefully there won't be too much more to do.

**Comment by benschwarz** [comment]
ST3 continues to throw either throw module errors that make little sense, or doesn't throw any errors at all (and the plugin isn't seemingly available). 

Any help here would be awesome folks

**Comment by pahlers** [comment]
Do you have a branch with the 'error' version?

**Pull request closed without merging**
